### ISSUE TITLE
User specifies Singularity image by filepath

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/jupyter-at-rc#19]
After selecting the desired profile from the spawner list, the user is prompted to specify the filepath of the Singularity image she wants to spawn. Facets of this interaction:
* The filepath input should validate that a valid path has been entered.
* This page should be distinct from the spawner select page.
* Once submitted if the filepath does not correspond to a valid image, re-render the page with an informative error.

**Comment by zebulasampedro** [comment]
The Nesting Spawner class that came out of #22 changes the motivation of this issue a bit. The ability to layer spawner config forms obviates the need to break the spawner workflow into multiple distinct pages, at least for the near- and mid-term.

@pbegeland I know you've been looking into inserting pages into the spawner workflow. Thoughts on the above?

**Comment by pbegeland** [comment]
@zebulasampedro I'll take a closer look at Nesting Spawner class and give you my opinion after that (Wednesday or Thursday. Thursday, Sep 21, more likely).
