### ISSUE TITLE
ipyparallel clusters tab appears even in the unsupported virtual notebook environment

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/jupyter-at-rc#35]
![screen shot 2017-09-26 at 8 49 11 am](https://user-images.githubusercontent.com/350294/30867149-6605c85c-a298-11e7-994c-c6cf5d00b9e3.png)

**Comment by zebulasampedro** [comment]
@anderbubble Did you follow the upgrade procedure in the User Guide (https://github.com/ResearchComputing/jupyter-at-rc/wiki/JupyterHub-User-Guide#updating-your-jupyterhub-config)?

The old Jupyter user config forced the tab to appear, and I suspect that it may be causing this issue. I cannot reproduce on my user account.

**Comment by anderbubble** [comment]
I hadn't. I've done that now, and now I just see the "Clusters" tab, which prompts you to install ipython-parallel

![screen shot 2017-09-26 at 9 16 11 am](https://user-images.githubusercontent.com/350294/30868295-6e65a8ca-a29b-11e7-8512-c14a887db308.png)

I suspect this is more to be expected; but it would be nice if even this clusters tab wasn't present in this circumstance. I don't know if that's possible without upstream changes, though.

**Comment by zebulasampedro** [comment]
The _Clusters_ tab with a prompt to install ipyparallel is built in to the newer versions of the notebook. It would require upstream changes.
